### PR TITLE
Add support Closure for 'query-logger' in DbalFactory.

### PR DESCRIPTION
**Pull request by vjik**
| Q             | A
| ------------- | ---
| Is bugfix?    |  ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | -

### CODE REVIEW

**Comment by xepozz** [comment]
What's the purpose of this PR?

**Comment by vjik** [comment]
> What's the purpose of this PR?

Ability to set `query-logger` as `Closure`.

**Comment by xepozz** [comment]
Do you have use-cases where it's needed?

**Comment by vjik** [comment]
For example, I want send to Cycle ORM separate Logger and configure him.

For yii-cycle I send:

```php
'query-logger' => static function(ContainerInterface $container) {
	$logger = new MyLogger();
	$logger->someThing('cycle-orm');
	return $logger;
}
```


For another package: 

```php
'logger' => static function(ContainerInterface $container) {
	$logger = new MyLogger();
	$logger->someThindg('another-package');
	return $logger;
}
```

**Comment by xepozz** [comment]
It should be done with usage Dependency Injection instead.
See https://github.com/yiisoft/docs/blob/master/guide/en/concept/di-container.md

**Comment by vjik** [comment]
I'm should set in container alias for my Logger class and use him as string for query-logger, right?

**Comment by xepozz** [comment]
Yes, it is.

**Comment by vjik** [comment]
Ok, I understand 👍 

May be remove Closure support in my PR and save refactoring and tests?

**Comment by xepozz** [comment]
I think it is better to make a new PR.

**Comment by vjik** [comment]
Ok! I will make it.

**Pull request closed without merging**
