### PR TITLE
Ability to disable/enable caching

### PR DESCRIPTION
**Pull request by rustamwin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | -

### CODE REVIEW

**Comment by rustamwin** [comment]
@roxblnfk slow testing :pensive:

**Comment by roxblnfk** [comment]
Even if you pass `false` as the parameter `$fromCache`, the cache will still be used. The Schema value in the cache just will be overwritten.
If you want to desable cache between requests then just pass `ArrayCache` as `CacheInteface`

**Comment by samdark** [comment]
What do you want to achieve disabling cache?

**Comment by rustamwin** [comment]
> What do you want to achieve disabling cache?

e.g: I want disable cache in development

**Comment by samdark** [comment]
So overall, @roxblnfk is correct. There's https://github.com/yiisoft/cache/blob/master/src/NullCache.php that you can pass to a component in order to disable caching.

**Comment by rustamwin** [comment]
then why do we need `$fromCache`?

**Comment by roxblnfk** [comment]
> then why do we need `$fromCache`?

This parameter can be used to force recalculation of the scheme with rewriting it in the cache.
If you want to use this parameter in the `OrmFactory` then first you need to come up with a more suitable name for the config option than `cache_enabled`

**Pull request closed without merging**
