### PR TITLE
Supporting for `Entity Behaviors`

### PR DESCRIPTION
**Pull request by roxblnfk**
| Q             | A
| ------------- | ---
| New feature?  | ✔️

Better compatibility with Cycle ORM v2:

- add `Entity Manager` definition
- support for `Entity Behaviors`

I didn't test it on demo

### CODE REVIEW

**Comment by samdark** [comment]
@roxblnfk would you please test it on demo?

**Comment by roxblnfk** [comment]
> @roxblnfk would you please test it on demo?

I am waiting for bugless demo :)

**Comment by samdark** [comment]
Merge it then.

**Comment by samdark** [comment]
Anything to be added to docs?

**Comment by roxblnfk** [comment]
> Anything to be added to docs?

Yes, but later. I think it would be good to add some documentation chunks after the custom collections supporting implementation

**Comment by samdark** [comment]
OK. Then feel free to merge it.

**Pull request merged**
